fixing

diff --git a/.github/workflows/docker-build-and-push.yml b/.github/workflows/docker-build-and-push.yml
--- a/.github/workflows/docker-build-and-push.yml
+++ b/.github/workflows/docker-build-and-push.yml
@@ -7,8 +7,7 @@ on:
   workflow_dispatch:
 
 env:
-  IMAGE_NAME: peacemaker283/docker-k8s-app
-
+  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/docker-k8s-project-app
 jobs:
   build-and-push:
     name: Build and Push Docker Image
@@ -20,6 +19,21 @@ jobs:
       # ======================
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Validate Docker Hub secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "::error::DOCKER_USERNAME secret is missing or empty"
+            exit 1
+          fi
+
+          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "::error::DOCKER_PASSWORD secret is missing or empty"
+            exit 1
+          fi
+
+          echo "Docker Hub secrets OK"
+
 
       # ======================
       # Setup Docker Buildx
